title: Christopher Tran
logo: /images/cd_workshop_2022.jpg
description: Data Scientist at the SEC
bio: <br>
  I am a Data Scientist at the U.S. Securities and Exchange Commission working on artificial intelligence and data science. I received my Ph.D. from the University of Illinois Chicago under the advisement of Elena Zheleva.
  <br><br>
  <a href="docs/chris_tran_resume.pdf"> Resume</a> (updated July 2026)
  <br>
  <div class="row">
    <div class="column">
      <a href="https://github.com/chris-tran-16"> <img src="files/github.png" alt="photo" style="width:32px;height:32px;float:left;margin-right:5px;"></a>
    </div>
    <div class="column">
      <a href="https://www.linkedin.com/in/christran16/"><img src="files/linkedin.png" alt="photo" style="width:32px;height:32px;float:left;margin-right:5px;"></a>
    </div>
    <div class="column">
      <a href="mailto:chris.l.tran@gmail.com"><img src="files/email.png" alt="photo" style="width:32px;height:32px;float:left;margin-right:5px;"></a>
    </div>
  </div>
  <br>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
color-scheme: dark
titles_from_headings:
  enabled: false
